spring:
  application:
    name: bienestarbank
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    password: bank
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090